# Generated by Django 6.0.1 on 2026-01-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(help_text='Используйте HTML для форматирования', verbose_name='Содержание урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на YouTube или Rutube видео', null=True, verbose_name='Ссылка на видео'),
        ),
    ]
