from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('research/', views.research_view, name='research'),
    path('themes/', views.themes_view, name='themes'),
    path('theme/<int:pk>/', views.theme_detail_view, name='theme_detail'),
    path('lesson/<int:lesson_id>/', views.lesson_detail_view, name='lesson_detail'),
    path('lesson/<int:lesson_id>/complete/', views.mark_lesson_completed, name='mark_lesson_completed'),
    path('theme/<int:theme_id>/add_lesson/', views.add_lesson_view, name='add_lesson'),
    path('lesson/<int:lesson_id>/add_task/', views.add_task_view, name='add_task'),
    path('research/', views.research_view, name='research'),
    path('research/youth/', views.research_youth_view, name='research_youth'),
    path('research/guide/', views.research_guide_view, name='research_guide'),
    path('lesson/<int:lesson_id>/add_interactive_task/',
         views.add_interactive_task, name='add_interactive_task'),
    path('task/<int:task_id>/add_questions/',
         views.add_questions, name='add_questions'),
    path('task/<int:task_id>/manage_questions/',
         views.manage_questions, name='manage_questions'),
    path('question/<int:question_id>/edit/',
         views.edit_question, name='edit_question'),
    path('task/<int:task_id>/take_quiz/',
         views.take_quiz, name='take_quiz'),
    path('quiz_results/<int:attempt_id>/',
         views.quiz_results, name='quiz_results'),
    path('task/<int:task_id>/retake/',
         views.retake_quiz, name='retake_quiz'),
]